# Generated by Django 3.1.2 on 2022-12-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PTT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(db_column='article_id', max_length=64, unique=True)),
                ('author', models.CharField(db_column='author', max_length=128, null=True)),
                ('title', models.CharField(db_column='title', max_length=256, null=True)),
                ('content', models.CharField(db_column='content', max_length=4096, null=True)),
                ('date', models.DateTimeField(db_column='date', null=True)),
                ('ip', models.CharField(db_column='ip', max_length=64, null=True)),
            ],
            options={
                'db_table': 'PTT',
            },
        ),
    ]
